name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install armmbed/formulae/arm-none-eabi-gcc
        brew install ldid
    - name: Build
      working-directory: ${{ github.workspace }}
      run: make arch=arm64
