name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
      id: runcmd
      with:
          arch: aarch64
          distro: macos-latest
