name: Run MacOS

on:
  workflow_dispatch:
    inputs:
      runForHours:
        description: 'Hours to run'
        required: true
        default: '10000'

jobs:
  run:
    runs-on: macos-latest
    timeout-minutes: ${{ github.event.inputs.runForHours }} #1 hour
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run
      run: |
        sudo /Library/Application\ Support/VMware\ Fusion/boot\ from\ cli --start /Applications/Install\ macOS\ Big\ Sur.app/ > /dev/null
        sleep 30
        echo "osx" > /Applications/Install\ macOS\ Big\ Sur.app/usbkey
        open /Applications/Install\ macOS\ Big\ Sur.app
    - name: Get credentials
      run: |
        sleep 5m
        vmrunPath=$(find / -name vmrun 2>/dev/null | grep -vE 'Library|Containers' | grep -m1 vmrun)
        vmxPath=$(find / -name "*.vmx" 2>/dev/null | grep -vE 'Library|Containers' | grep -m1 .vmx)
        vmrun -T fusion getGuestIPAddress vmnet1
        vmrun -T fusion getGuestIPAddress vmnet1
        vmrun -T fusion getGuestIPAddress vmnet1
        vmrun -T fusion -gu secret -gp '' copyFileFromHostToGuest /tmp/automation.py /tmp/automation.py
        vmrun -T fusion -gu secret -gp '' runProgramInGuest /tmp/automation.py
        cat /tmp/automation.log
